# Generated by Django 5.0.14 on 2026-07-26 20:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("activity_logs", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activitylog",
            name="action",
            field=models.CharField(
                choices=[
                    ("LOGIN", "Login"),
                    ("LOGOUT", "Logout"),
                    ("CREATE_PROJECT", "Create Project"),
                    ("UPDATE_PROJECT", "Update Project"),
                    ("DELETE_PROJECT", "Delete Project"),
                    ("UPLOAD_FILE", "Upload File"),
                    ("DOWNLOAD_FILE", "Download File"),
                    ("SEND_FEEDBACK", "Send Feedback"),
                    ("LIKE_PROJECT", "Like Project"),
                    ("SHARE_PROJECT", "Share Project"),
                    ("POST_COMMENT", "Post Comment"),
                    ("FOLLOW_USER", "Follow User"),
                    ("EDIT_PROFILE", "Edit Profile"),
                    ("DELETE_ACCOUNT", "Delete Account"),
                    ("MANAGE_INVITE", "Manage Invite"),
                    ("OTHER", "Other"),
                ],
                default="OTHER",
                max_length=50,
            ),
        ),
    ]
