# Generated by Django 5.0.14 on 2026-07-25 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_bio_alter_customuser_profile_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="avatar_seed",
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
