[mypy]
plugins = mypy_django_plugin.main
python_version = 3.11
ignore_missing_imports = True

files = users,projects,dashboard,feedback,notifications,search,activity_logs,skill_sphere,theme

exclude = (^|[\\/])migrations([\\/])

[mypy.plugins.django-stubs]
django_settings_module = skill_sphere.settings.development