# Generated by Django 5.0.14 on 2026-07-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_fe_user_id_3075a3_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_fe_status_35d074_idx",
        ),
        migrations.RemoveIndex(
            model_name="feedback",
            name="feedback_fe_categor_9a32a3_idx",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="admin_response",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="category",
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_reply",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="rating",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[
                    ("suggestion", "Suggestion"),
                    ("bug", "Bug Report"),
                    ("feature", "Feature Request"),
                    ("praise", "Praise"),
                ],
                default="suggestion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("reviewed", "Reviewed"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
