# Generated by Django 5.0.14 on 2026-07-27 14:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0002_alter_feedback_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="feedback",
            options={"ordering": ["-created_at"]},
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="admin_reply",
        ),
        migrations.RemoveField(
            model_name="feedback",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="feedback",
            name="votes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="message",
            field=models.TextField(max_length=2000),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="rating",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("in_review", "In Review"),
                    ("planned", "Planned"),
                    ("resolved", "Resolved"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="subject",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="type",
            field=models.CharField(
                choices=[
                    ("suggestion", "💡 Suggestion"),
                    ("bug", "🐛 Bug Report"),
                    ("feature", "✨ Feature Request"),
                    ("praise", "🎉 Praise"),
                ],
                default="suggestion",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="feedback",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feedbacks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
