# Generated by Django 5.0.14 on 2026-07-27 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "feedback",
            "0003_alter_feedback_options_remove_feedback_admin_reply_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="admin_reaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "بدون ری\u200cاکشن"),
                    ("👍", "👍 موافقم"),
                    ("❤️", "❤️ عالیه"),
                    ("👀", "👀 بررسیش می\u200cکنیم"),
                    ("🎉", "🎉 انجام شد"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
