# Generated by Django 5.0.14 on 2026-07-27 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0004_feedback_admin_reaction"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feedback",
            name="admin_reaction",
            field=models.CharField(
                blank=True,
                choices=[
                    ("", "No Reaction"),
                    ("👍", "👍 Agree"),
                    ("❤️", "❤️ Great"),
                    ("👀", "👀 We'll Review"),
                    ("🎉", "🎉 Done"),
                ],
                default="",
                max_length=10,
            ),
        ),
    ]
