# Generated by Django 5.0.14 on 2026-07-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0005_alter_feedback_admin_reaction"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="votes",
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="feedback",
            name="admin_response",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
