# Generated by Django 5.0.14 on 2026-07-27 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("feedback", "0006_remove_feedback_votes_feedback_admin_responded_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="admin_responded_at",
        ),
    ]
