# Generated by Django 5.0.14 on 2026-07-27 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("feedback", "0007_remove_feedback_admin_responded_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="admin_responded_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
