# Generated by Django 5.0.14 on 2026-06-17 00:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="title",
            field=models.CharField(max_length=255),
        ),
    ]
