# Generated by Django 5.0.14 on 2026-06-18 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_notification_type_alter_notification_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("comment", "Comment"),
                    ("feedback", "Feedback"),
                    ("invite", "Invite"),
                    ("member", "Member"),
                    ("follow", "Follow"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]