# Generated by Django 5.0.14 on 2026-07-27 13:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0003_notification_link_alter_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="type",
            field=models.CharField(
                choices=[
                    ("project", "Project"),
                    ("comment", "Comment"),
                    ("feedback", "Feedback"),
                    ("invite", "Invite"),
                    ("member", "Member"),
                    ("follow", "Follow"),
                    ("like", "Like"),
                    ("system", "System"),
                ],
                default="system",
                max_length=20,
            ),
        ),
    ]
